# ── Database master password ──
# Generated by Terraform, stored only in Secrets Manager. Never appears in
# state outputs, env vars, or your shell. The ECS task definition (Phase 3d)
# will reference the secret ARN — Fargate pulls the value at task startup.
resource "random_password" "db_master" {
  length      = 32
  special     = true
  # RDS Postgres master password disallows /, @, ", and spaces.
  override_special = "!#$%&*()-_=+[]{}<>:?"
}

resource "aws_secretsmanager_secret" "db_master" {
  name        = "aeglero-emr/db-master-password"
  description = "RDS Postgres master user — created by Terraform, used by ECS at runtime"
  kms_key_id  = aws_kms_key.secrets.id

  # 7-day recovery window = standard. Lets you undelete within a week if you
  # `terraform destroy` then change your mind.
  recovery_window_in_days = 0
}

resource "aws_secretsmanager_secret_version" "db_master" {
  secret_id = aws_secretsmanager_secret.db_master.id

  # Stored as JSON so the consumer (RDS resource in Phase 3c, then ECS task in
  # Phase 3d) can grab username and password independently.
  secret_string = jsonencode({
    username = var.db_username
    password = random_password.db_master.result
  })
}

# ── Flask SECRET_KEY ──
# Used by Flask to sign sessions and cookies. Rotating this invalidates all
# active sessions, which is the point — for periodic forced re-auth.
resource "random_password" "flask_secret_key" {
  length  = 64
  special = false # alphanumeric is safest for env-var passing
}

resource "aws_secretsmanager_secret" "flask_secret_key" {
  name        = "aeglero-emr/flask-secret-key"
  description = "Flask SECRET_KEY for session signing"
  kms_key_id  = aws_kms_key.secrets.id

  recovery_window_in_days = 0
}

resource "aws_secretsmanager_secret_version" "flask_secret_key" {
  secret_id     = aws_secretsmanager_secret.flask_secret_key.id
  secret_string = random_password.flask_secret_key.result
}

# ── DATABASE_URL — composed connection string ──
# Constructed once here so the app receives a single env var rather than 5
# pieces. The secret is KMS-encrypted in Secrets Manager; ECS pulls and
# injects it as DATABASE_URL at task startup. ?sslmode=require pairs with
# rds.force_ssl=1 on the parameter group so connections fail fast if TLS
# isn't negotiated.
resource "aws_secretsmanager_secret" "database_url" {
  name        = "aeglero-emr/database-url"
  description = "Composed Postgres URL for the app to consume directly"
  kms_key_id  = aws_kms_key.secrets.id

  recovery_window_in_days = 0
}

resource "aws_secretsmanager_secret_version" "database_url" {
  secret_id = aws_secretsmanager_secret.database_url.id
  secret_string = format(
    "postgresql+psycopg2://%s:%s@%s:%d/%s?sslmode=require",
    var.db_username,
    random_password.db_master.result,
    aws_db_instance.main.address,
    aws_db_instance.main.port,
    aws_db_instance.main.db_name,
  )
}
