# ── Database master password ──
# Generated by Terraform, stored only in Secrets Manager. The ECS task pulls
# the value at task startup via the executionRole.
resource "random_password" "db_master" {
  length      = 32
  special     = true
  # RDS Postgres master password disallows /, @, ", and spaces.
  override_special = "!#$%&*()-_=+[]{}<>:?"
}

resource "aws_secretsmanager_secret" "db_master" {
  # checkov:skip=CKV2_AWS_57: Rotation deferred; see docs/iac-scan-exceptions.md.
  name        = "aeglero-emr/db-master-password"
  description = "RDS Postgres master credentials"
  kms_key_id  = aws_kms_key.secrets.id

  # 0 = immediate deletion on destroy. Adjust for production recovery windows.
  recovery_window_in_days = 0
}

resource "aws_secretsmanager_secret_version" "db_master" {
  secret_id = aws_secretsmanager_secret.db_master.id

  # JSON so the consumer can read username and password independently.
  secret_string = jsonencode({
    username = var.db_username
    password = random_password.db_master.result
  })
}

# ── Flask SECRET_KEY ──
# Used to sign sessions and cookies. Rotating this invalidates all active
# sessions, forcing re-authentication.
resource "random_password" "flask_secret_key" {
  length  = 64
  special = false
}

resource "aws_secretsmanager_secret" "flask_secret_key" {
  # checkov:skip=CKV2_AWS_57: Rotation deferred; see docs/iac-scan-exceptions.md.
  name        = "aeglero-emr/flask-secret-key"
  description = "Flask SECRET_KEY for session signing"
  kms_key_id  = aws_kms_key.secrets.id

  recovery_window_in_days = 0
}

resource "aws_secretsmanager_secret_version" "flask_secret_key" {
  secret_id     = aws_secretsmanager_secret.flask_secret_key.id
  secret_string = random_password.flask_secret_key.result
}

# ── DATABASE_URL — composed connection string ──
# Pre-assembled here so the app receives a single env var. Pairs with
# rds.force_ssl=1 on the parameter group so non-TLS connections fail fast.
resource "aws_secretsmanager_secret" "database_url" {
  # checkov:skip=CKV2_AWS_57: Rotates implicitly with db_master.
  name        = "aeglero-emr/database-url"
  description = "Composed Postgres connection URL"
  kms_key_id  = aws_kms_key.secrets.id

  recovery_window_in_days = 0
}

resource "aws_secretsmanager_secret_version" "database_url" {
  secret_id = aws_secretsmanager_secret.database_url.id
  secret_string = format(
    "postgresql+psycopg2://%s:%s@%s:%d/%s?sslmode=require",
    var.db_username,
    random_password.db_master.result,
    aws_db_instance.main.address,
    aws_db_instance.main.port,
    aws_db_instance.main.db_name,
  )
}
