"""add admission discharge fields to patient

Revision ID: 3add2cd44a0c
Revises: 4f4a961cefd5
Create Date: 2026-03-07 05:04:26.086169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3add2cd44a0c'
down_revision = '4f4a961cefd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admitted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('discharged_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('discharge_reason', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('discharge_reason')
        batch_op.drop_column('discharged_at')
        batch_op.drop_column('admitted_at')

    # ### end Alembic commands ###
