"""add recurring fields to form_template

Revision ID: 4f4a961cefd5
Revises: 6202a128144e
Create Date: 2026-03-07 03:02:29.219578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f4a961cefd5'
down_revision = '6202a128144e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_recurring', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('recurrence_value', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('recurrence_unit', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_template', schema=None) as batch_op:
        batch_op.drop_column('recurrence_unit')
        batch_op.drop_column('recurrence_value')
        batch_op.drop_column('is_recurring')

    # ### end Alembic commands ###
